### ISSUE TITLE
Empty dictionary tables after a fresh install

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/dolibarr_ynh#11]
When install works (cf. #10 , maybe related ?), dictionary tables (_ynh_c_currencies_, _ynh_c_country_, ...) are empty.

I don't know how to investigate further
```
# yunohost --version
yunohost: 
  repo: stable
  version: 2.7.10
yunohost-admin: 
  repo: stable
  version: 2.7.7
moulinette: 
  repo: stable
  version: 2.7.7
ssowat: 
  repo: stable
  version: 2.7.7

```

**Comment by mastereur** [comment]
I think that this issue is no longer relevant since the last message and the reworking (after July 05, 2019).

**Comment by mastereur** [comment]
closed due to inactivity

**Comment by SiM** [comment]
Hi,

Some dictionary tables are still empty after a fresh install (which displays an error message when selecting a country for the first time on `admin/company.php`).

I have identified the following tables: 

- llx_c_regions
- llx_c_departements
- llx_c_tva

I have done a standard Dolibarr install without YNH and theses tables are are properly filled in.

```
# yunohost --version
yunohost: 
  repo: stable
  version: 4.0.8
yunohost-admin: 
  repo: stable
  version: 4.0.4
moulinette: 
  repo: stable
  version: 4.0.3
ssowat: 
  repo: stable
  version: 4.0.4.1
```

Dolibarr version: `12.0.3~ynh1`
